package:
  name: test_conda_packaging_lrlunin
  version: 1.0.1

source:
  path: ../

requirements:
  build:
    - python
  run:
    - python
    - pytango>=9.3.6
    - numpy>=1.24.1
    - pyzmq>=23.2.0
    - pillow>=9.3.0

about:
  home: https://github.com/lrlunin/test_actions_repo
